### ISSUE TITLE
에디터 적용하면서 나타나는 문제점

### ISSUE THREAD

**Issue by saseungmin** [CodeSoom/project-react-2-saseungmin#31]
### 🤔 고민사항 #30 

- [ ] 테스트를 어떻게 통과시켜야 할지 모르겠다. ([링크](https://github.com/CodeSoom/project-react-2-saseungmin/pull/30#discussion_r531159068))
- [x] 컴포넌트 안에 CSS를 불러올때의 문제점 ([링크](https://github.com/CodeSoom/project-react-2-saseungmin/pull/30#discussion_r531165153)) - 해결

**Comment by Kihyun92** [comment]
커버리지 100% 달성하는 것도 중요하지만, 너무 집착하지 않으셔도 괜찮을 것 같습니다. 테스트를 하지말라는 뜻이 아니라, 외부 라이브러리의 경우 우리가 통제할 수 있는 부분이 아니므로 테스트를 작성했을때의 이득을 잘 따져보시면 좋을 것 같다는 말씀 드리고 싶네요~ ☺️
