### ISSUE TITLE
스터디를 신청할 때 다짐도 기록할 수 있으면 좋을 것 같아요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-saseungmin#52]
스터디를 신청할 때 신청서를 받아서 무엇을 얻어가려고 하는지 기록할 수 있도록 하면 좋을 것 같습니다.

**Comment by saseungmin** [comment]
- 넵! 좋은 생각인거 같습니다!
- 또한, 바로 스터디 그룹의 모집하는 주최자가 신청자를 확인 후 참여할 수 있게 변경해보겠습니다!
