### ISSUE TITLE
스터디 마감이 몇일 남았는지도 보여주면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-saseungmin#53]
현재 날짜를 보여주고 있지만 마감이 얼마 남았는지도 표시해주면 좋을 것 같아요

![image](https://user-images.githubusercontent.com/14071105/100889883-fdd51280-34fa-11eb-87eb-4ebf1cf983fb.png)

마감 3일전! 처럼요

**Comment by saseungmin** [comment]
- 소개 페이지에는 

![image](https://user-images.githubusercontent.com/60910665/100891622-cd8e7380-34fc-11eb-9caa-efcb0c803c97.png)

시간이 얼마 남았는지 나오는데 목록에도 그렇게 해주는게 좋을까요??

**Comment by hannut91** [comment]
목록에서도 보여야 클릭하고 싶어질 것 같아요 ㅎㅎ

**Comment by saseungmin** [comment]
넵 알겠습니다! 🙏

**Comment by saseungmin** [comment]
- 스터디 목록에 마감일 구현 #80
