### ISSUE TITLE
내가 개설한 스터디에도 내가 참여가 됩니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-saseungmin#54]
내가 개설한 스터디에는 본인은 참여가 안되게 해야 될 것 같아요

**Comment by saseungmin** [comment]
이부분은 변경을 해주었습니다!
현재 배포된 소스에는 미반영되어 있는거 같습니다!
현재 작성자의 아이디가 하드코딩으로 무조건 `user1`로 들어갑니다! 그렇기 때문에 체크하는 로직에서 확인을 못해줍니다.
변경된 소스에서는 버튼 부분을 안보이게 막아줬습니다.
