### ISSUE TITLE
스터디를 하나밖에 개설하지 못합니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-saseungmin#55]
여러개의 스터디를 진행할 수도 있으니 스터디를 여러개 진행할 수 있으면 좋을 것 같아요

**Comment by saseungmin** [comment]
앗! 글작성 후 리턴 받은 groupId가 존재하면 history push를 해주는데 바로 해주는데, 소개 페이지로 이동 후 `unmount` 할 때 groupId 값을 안비워줘서 글을 다시 작성할 때 계속 같은 페이지로 이동하는 거 같습니다.
수정하겠습니다.

**Comment by gringrape** [comment]
저는 왜 스터디 개설이 안될까요? ㅜ
태그를 입력하는 방법이 따로 있나요?
태그를 입력하세요 라고 나오네요

**Comment by saseungmin** [comment]
저것도 수정해야 할 거 같습니다 ㅋㅋㅋ
저거 태그 입력할 때 `keypress.enter`로 해놔서.. `enter`를 처야지 태그가 입력되고 저 등록 버튼은 **글 등록 버튼**입니다.
저도 아까 제가 만들어놓고 왜 안되지??? 이랬다는...

**Comment by gringrape** [comment]
아 그렇군요 ㅋㅋㅋ 개설해봐야 겠네요 ㅎㅎ
