### ISSUE TITLE
스터디 취소를 할 수 있으면 좋을 것 같아요.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-saseungmin#76]
저는 신청하면 빼도박도 못하는건 각자의 사정이 있으니까요 
![99819276-9cc04d00-2b92-11eb-80f3-cb00220f04be](https://user-images.githubusercontent.com/14071105/101285883-0d21cc00-382b-11eb-8406-7461d6a73bbe.jpg)

**Comment by saseungmin** [comment]
넵 취소기능도 구현하겠습니다 🙏

**Comment by saseungmin** [comment]
- 취소 기능 구현 #81
