### ISSUE TITLE
스터디를 신청한 사람들은 어디서 확인하나요?

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-saseungmin#92]
제가 스터디를 모집했는데 참여한 사람들 목록은 어떻게 확인할 수 있나요?
승인이나 거절을 할 수 있나요?

**Comment by saseungmin** [comment]
넵 현재 구현중에 있습니다. 
승인과 거절을 할 수 있게 할려고 합니다!

**Comment by saseungmin** [comment]
- 작업 진행중 
스터디 신청자 목록 #93
